--User table for logging in
create table AccountData
(
	ACCOUNTDATA_KEY		int				IDENTITY,
	EMAIL_ADDRESS		varchar(100)	NOT NULL,
	LOGIN_SECRET		varchar(1000)	NOT NULL,
	LOGIN_SALT			varchar(1000)	NOT NULL,

	CONSTRAINT Q_ACCOUNTDATA_ACCOUNTDATA_KEY_00001 PRIMARY KEY (ACCOUNTDATA_KEY),
	CONSTRAINT Q_ACCOUNTDATA_EMAIL_ADDRESS_00001 UNIQUE (EMAIL_ADDRESS)
)