create table ChangeLog
(
	LOG_KEY				int				IDENTITY,
	LOG_TABLE			varchar(50)		NOT NULL,
	TABLE_KEY			int				NOT NULL,
	LOG_DATA			varchar(8000)	NOT NULL DEFAULT '',
	LOG_DTTM			DateTime2		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	
	CONSTRAINT Q_CHANGELOG_LOG_KEY_00001 PRIMARY KEY (LOG_KEY)
)