--The user maintained email schedule
create table EmailSchedule
(
	SCHEDULE_KEY		int				IDENTITY,
	ACCOUNTDATA_KEY		int				NOT NULL,
	RECORD_STATUS		char(1)			NOT NULL DEFAULT '',
	CREATED_DTTM		DateTime2		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	LAST_UPDATED_DTTM	DateTime2		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	SCHEDULED_TIME		time			NULL,
	RECURS_UNTIL_DTTM	DateTime2		NULL,
	LAST_RUN_DTTM		DateTime2		NULL,
	--Accepted values: YEAR,MONTH,WEEK,DAY,HOUR,MINUTE
	RUN_INTERVAL		varchar(30)		NOT NULL DEFAULT '',
	INTERVAL_VALUE		int				NOT NULL DEFAULT 0,
	--Format {Sunday, Monday, Tuesday, Wednesday, Thursday, Friday, Saturday} (Y/N): NYYYYYN
	DAY_SELECT			char(7)			NOT NULL DEFAULT '',
	EMAIL_MESSAGE		varchar(4000)	NOT NULL DEFAULT '',

	CONSTRAINT Q_EMAILSCHEDULE_SCHEDULE_KEY_00001 PRIMARY KEY (SCHEDULE_KEY),
	CONSTRAINT FK_EMAILSCHEDULE_ACCOUNTDATA_KEY_00001 FOREIGN KEY (ACCOUNTDATA_KEY) REFERENCES AccountData(ACCOUNTDATA_KEY)
)