--Server email accounts for doing the actual sending of email
create table HostEmailAccounts
(
	HOST_KEY			int				IDENTITY,
	SMTP_HOST			varchar(100)	NOT NULL,
	SMTP_PORT			int				NOT NULL,
	SMTP_USER			varchar(100)	NOT NULL,
	SMTP_PASSWORD		varchar(1000)	NOT NULL,
	USE_SSL				char(1)			NOT NULL DEFAULT '',
	RECORD_STATUS		char(1)			NOT NULL DEFAULT '',
	DAILY_LIMIT			int				NOT NULL DEFAULT 0,
	DAILY_SENT			int				NOT NULL DEFAULT 0,
	TOTAL_SENT			numeric(9,0)	NOT NULL DEFAULT 0,

	CONSTRAINT Q_HOSTEMAILACCOUNTS_HOST_KEY_00001 PRIMARY KEY (HOST_KEY),
	CONSTRAINT Q_HOSTEMAILACCOUNTS_HOST_USER_00001 UNIQUE (SMTP_HOST, SMTP_USER)
)