--After an email is successfully sent insert a record here
create table SentEmailsHistory
(
	EMAIL_KEY			int				IDENTITY,
	SCHEDULE_KEY		int				NOT NULL,
	MSG_ID				varchar(250)	NOT NULL DEFAULT '',
	TO_ADDRESS			varchar(1000)	NOT NULL DEFAULT '',
	HOST_KEY			int				NOT NULL,
	CREATED_DTTM		DateTime2		NOT NULL DEFAULT CURRENT_TIMESTAMP,
	EMAIL_MESSAGE		varchar(4000)	NOT NULL DEFAULT '',

	CONSTRAINT Q_SENTEMAILHISTORY_EMAIL_KEY_00001 PRIMARY KEY (EMAIL_KEY),
	CONSTRAINT FK_SENTEMAILHISTORY_SCHEDULE_KEY_00001 FOREIGN KEY (SCHEDULE_KEY) REFERENCES EmailSchedule(SCHEDULE_KEY),
	CONSTRAINT FK_SENTEMAILHISTORY_HOST_KEY_00001 FOREIGN KEY (HOST_KEY) REFERENCES HostEmailAccounts(HOST_KEY)
)